/*
 * SPDX-FileCopyrightText: 2025 Pexip AS
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int32planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/pexip/go-infinity-sdk/v38/config"
)

var (
	_ resource.ResourceWithImportState = (*InfinityOAuth2ClientResource)(nil)
)

type InfinityOAuth2ClientResource struct {
	InfinityClient InfinityClient
}

type InfinityOAuth2ClientResourceModel struct {
	ID            types.String `tfsdk:"id"`
	ResourceID    types.Int32  `tfsdk:"resource_id"`
	ClientID      types.String `tfsdk:"client_id"`
	ClientName    types.String `tfsdk:"client_name"`
	Role          types.String `tfsdk:"role"`
	PrivateKeyJWT types.String `tfsdk:"private_key_jwt"`
}

func (r *InfinityOAuth2ClientResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_infinity_oauth2_client"
}

func (r *InfinityOAuth2ClientResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	p, ok := req.ProviderData.(*PexipProvider)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *PexipProvider, got: %T. Please report this issue to the provider developers", req.ProviderData),
		)
		return
	}

	r.InfinityClient = p.client
}

func (r *InfinityOAuth2ClientResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource URI for the OAuth2 client",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"resource_id": schema.Int32Attribute{
				Computed:            true,
				MarkdownDescription: "The resource integer identifier for the OAuth2 client",
				PlanModifiers: []planmodifier.Int32{
					int32planmodifier.UseStateForUnknown(),
				},
			},
			"client_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The OAuth2 client identifier generated by the system",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"client_name": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
					stringvalidator.LengthAtMost(100),
				},
				MarkdownDescription: "The name of the OAuth2 client. Maximum length: 100 characters.",
			},
			"role": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
				MarkdownDescription: "The role URI to assign to this OAuth2 client for authorization.",
			},
			"private_key_jwt": schema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				MarkdownDescription: "The private key JWT for the OAuth2 client. This field is sensitive and computed.",
			},
		},
		MarkdownDescription: "Manages an OAuth2 client. OAuth2 clients are used for API access and automation, providing secure authentication for external applications.",
	}
}

func (r *InfinityOAuth2ClientResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	plan := &InfinityOAuth2ClientResourceModel{}

	resp.Diagnostics.Append(req.Plan.Get(ctx, plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createRequest := &config.OAuth2ClientCreateRequest{
		ClientName: plan.ClientName.ValueString(),
		Role:       plan.Role.ValueString(),
	}

	createResponse, err := r.InfinityClient.Config().CreateOAuth2Client(ctx, createRequest)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Creating Infinity OAuth2 client",
			fmt.Sprintf("Could not create Infinity OAuth2 client: %s", err),
		)
		return
	}

	// Extract the numeric ID from the response for use in Read/Update/Delete operations
	resourceID, err := createResponse.ResourceID()
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Retrieving Infinity OAuth2 client ID",
			fmt.Sprintf("Could not retrieve ID for created Infinity OAuth2 client: %s", err),
		)
		return
	}

	// Unmarshal the response body to get the full OAuth2Client including private_key_jwt
	// which is only returned on creation
	var srv config.OAuth2Client
	if err := json.Unmarshal(createResponse.Body, &srv); err != nil {
		resp.Diagnostics.AddError(
			"Error Parsing Created Infinity OAuth2 client",
			fmt.Sprintf("Could not parse created Infinity OAuth2 client response: %s", err),
		)
		return
	}

	model := &InfinityOAuth2ClientResourceModel{
		ID:         types.StringValue(srv.ResourceURI),
		ResourceID: types.Int32Value(int32(resourceID)), // #nosec G115 -- API values are expected to be within int32 range
		ClientID:   types.StringValue(srv.ClientID),
		ClientName: types.StringValue(srv.ClientName),
		Role:       types.StringValue(srv.Role),
	}

	// private_key_jwt is only returned on creation
	if srv.PrivateKeyJWT != "" {
		model.PrivateKeyJWT = types.StringValue(srv.PrivateKeyJWT)
	} else {
		model.PrivateKeyJWT = types.StringNull()
	}

	tflog.Trace(ctx, fmt.Sprintf("created Infinity OAuth2 client with ID: %s, name: %s", model.ID, model.ClientName))

	resp.Diagnostics.Append(resp.State.Set(ctx, model)...)
}

func (r *InfinityOAuth2ClientResource) read(ctx context.Context, resourceID string) (*InfinityOAuth2ClientResourceModel, error) {
	var data InfinityOAuth2ClientResourceModel

	srv, err := r.InfinityClient.Config().GetOAuth2Client(ctx, resourceID)
	if err != nil {
		return nil, err
	}

	if srv.ResourceURI == "" {
		return nil, fmt.Errorf("OAuth2 client with ID %s not found", resourceID)
	}

	data.ID = types.StringValue(srv.ResourceURI)
	data.ClientID = types.StringValue(srv.ClientID)
	data.ClientName = types.StringValue(srv.ClientName)
	data.Role = types.StringValue(srv.Role)

	// Note: private_key_jwt is only returned on creation, not on reads
	// We don't set it here to preserve the value from creation in state

	return &data, nil
}

func (r *InfinityOAuth2ClientResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	state := &InfinityOAuth2ClientResourceModel{}

	resp.Diagnostics.Append(req.State.Get(ctx, state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resourceID := fmt.Sprintf("%d", state.ResourceID.ValueInt32())
	// Save private_key_jwt before reading
	savedPrivateKeyJWT := state.PrivateKeyJWT

	newState, err := r.read(ctx, resourceID)
	if err != nil {
		// Check if the error is a 404 (not found)
		if isNotFoundError(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(
			"Error Reading Infinity OAuth2 client",
			fmt.Sprintf("Could not read Infinity OAuth2 client: %s", err),
		)
		return
	}

	newState.ResourceID = state.ResourceID
	// Preserve private_key_jwt from previous state since it's only returned on creation
	newState.PrivateKeyJWT = savedPrivateKeyJWT

	resp.Diagnostics.Append(resp.State.Set(ctx, newState)...)
}

func (r *InfinityOAuth2ClientResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	plan := &InfinityOAuth2ClientResourceModel{}
	state := &InfinityOAuth2ClientResourceModel{}

	resp.Diagnostics.Append(req.Plan.Get(ctx, plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateRequest := &config.OAuth2ClientUpdateRequest{
		ClientName: plan.ClientName.ValueString(),
		Role:       plan.Role.ValueString(),
	}

	resourceID := fmt.Sprintf("%d", state.ResourceID.ValueInt32())
	_, err := r.InfinityClient.Config().UpdateOAuth2Client(ctx, resourceID, updateRequest)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Updating Infinity OAuth2 client",
			fmt.Sprintf("Could not update Infinity OAuth2 client: %s", err),
		)
		return
	}

	// Read the state from the API to get all computed values
	model, err := r.read(ctx, resourceID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Reading Updated Infinity OAuth2 client",
			fmt.Sprintf("Could not read updated Infinity OAuth2 client with ID %s: %s", resourceID, err),
		)
		return
	}

	model.ResourceID = state.ResourceID
	// Preserve private_key_jwt from state since it's only returned on creation
	model.PrivateKeyJWT = state.PrivateKeyJWT

	resp.Diagnostics.Append(resp.State.Set(ctx, model)...)
}

func (r *InfinityOAuth2ClientResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	state := &InfinityOAuth2ClientResourceModel{}

	tflog.Info(ctx, "Deleting Infinity OAuth2 client")

	resp.Diagnostics.Append(req.State.Get(ctx, state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.InfinityClient.Config().DeleteOAuth2Client(ctx, fmt.Sprintf("%d", state.ResourceID.ValueInt32()))

	// Ignore 404 Not Found and Lookup errors on delete
	if err != nil && !isNotFoundError(err) && !isLookupError(err) {
		resp.Diagnostics.AddError(
			"Error Deleting Infinity OAuth2 client",
			fmt.Sprintf("Could not delete Infinity OAuth2 client with ID %s: %s", state.ID.ValueString(), err),
		)
		return
	}
}

func (r *InfinityOAuth2ClientResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resourceID, err := strconv.Atoi(req.ID)
	if err != nil {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Import ID must be a valid integer for the resource ID. Got: %s", req.ID),
		)
		return
	}

	tflog.Trace(ctx, fmt.Sprintf("Importing Infinity OAuth2 client with resource ID: %d", resourceID))

	// Read the resource from the API
	model, err := r.read(ctx, req.ID)
	if err != nil {
		if isNotFoundError(err) {
			resp.Diagnostics.AddError(
				"Infinity OAuth2 Client Not Found",
				fmt.Sprintf("Infinity OAuth2 client with resource ID %d not found.", resourceID),
			)
			return
		}
		resp.Diagnostics.AddError(
			"Error Importing Infinity OAuth2 Client",
			fmt.Sprintf("Could not import Infinity OAuth2 client with resource ID %d: %s", resourceID, err),
		)
		return
	}

	model.ResourceID = types.Int32Value(int32(resourceID)) // #nosec G115 -- API values are expected to be within int32 range

	resp.Diagnostics.Append(resp.State.Set(ctx, model)...)
}
